Merge patch-deps_v8_src_codegen_riscv64_assembler-riscv64_cc
This patch is apparently to fix the following compile error
on riscv:

../deps/v8/src/codegen/riscv64/assembler-riscv64.cc:403:22: error: reinterpret_cast from 'v8::internal::Address' (aka 'unsigned long') to 'uint64_t' (aka 'unsigned long long') is not allowed

Quoting from the origianl patch:

"Use static_cast instead of a potentially dangerous reinterpret_cast.
Doesn't matter since this file only supports riscv64 where unsigned long and
unsigned long long are actually the same size."